### ISSUE TITLE
Repository's About info

### ISSUE THREAD

**Issue by sadikkuzu** [peaceiris/hugo-extended-docker#129]
After 0.111.2 release, is it `Alpine&Debian Based Docker Image for Hugo`?

https://github.com/peaceiris/hugo-extended-docker/blob/92114d5cea3db209baa3cc8a93ad353ee54eec09/Makefile#L70

<a href="https://github.com/peaceiris/hugo-extended-docker"><img width="315" alt="image" src="https://user-images.githubusercontent.com/23168063/224477896-8efab463-3951-488e-ae6a-9873bcc6b36b.png"></a>

**Comment by peaceiris** [comment]
Yes, alpine has been replaced with Debian. Nice catch! Thanks.
