### ISSUE TITLE
User name setting in the push and image update yml

### ISSUE THREAD

**Issue by Adeljoo** [peaceiris/hugo-extended-docker#3]
Can I ask about the DOCKER_HUB_BASE_NAME is set to your name right now, should I change it to my username? how about the following line
echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u (**your username**) --password-stdin

**Comment by peaceiris** [comment]
This is a basic Docker registry specification. You need to do as follows on the GitHub Actions runner:

```sh
echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u Adeljoo --password-stdin
```

Do not ask here, go to the forum.
